@extends('backend.master-tailwind')
@section('title', __('reporting.daily_summary').' · '.$data['shop_label'].' · '.$row->business_date.' · v'.$row->version)
@section('content')
    <p class="mb-3">{{ __('reporting.'.($row->closure_type === 'corrected' ? 'corrected_available' : 'day_closed')) }}</p>
    <p class="mb-3">{{ __('reporting.cutoff_at') }}: {{ \Carbon\CarbonImmutable::parse($row->cutoff_at, 'UTC')->setTimezone('Africa/Douala')->format('Y-m-d H:i:s') }} · {{ __('reporting.immutable') }}</p>
    <div class="my-3 flex flex-wrap gap-2">@foreach($versions as $v)<a class="qpos-button qpos-button-secondary qpos-button-md" href="{{ route('backend.admin.reporting.summary',$v->id) }}">v{{ $v->version }} · {{ __('reporting.'.$v->closure_type) }}</a>@endforeach<a class="qpos-button qpos-button-secondary qpos-button-md" href="{{ route('backend.admin.reporting.summary-export',['id'=>$row->id,'format'=>'pdf']) }}">{{ __('reporting.export_pdf') }}</a></div>
    @include('backend.reporting.metrics', ['summary'=>$data['summary']])
    <x-backend.card :title="__('reporting.open_sessions')"><ul>@foreach($data['open_sessions'] as $s)<li>#{{ $s['id'] }} · {{ $s['name'] }}</li>@endforeach</ul></x-backend.card>
    <x-backend.card :title="__('reporting.late_activity')"><div class="overflow-x-auto"><table class="qpos-table w-full text-sm"><thead><tr><th>{{ __('reporting.occurred_at') }}</th><th>{{ __('reporting.event_kind') }}</th><th>ID</th><th>{{ __('reporting.amount') }}</th></tr></thead><tbody>@forelse($late as $a)<tr><td class="p-2">{{ \Carbon\CarbonImmutable::parse($a->occurred_at,'UTC')->setTimezone('Africa/Douala')->format('Y-m-d H:i:s') }}</td><td class="p-2">{{ __('reporting.'.$a->event_kind) }}</td><td class="p-2">{{ $a->source_id }}</td><td class="p-2">{{ $a->net_sales }}</td></tr>@empty<tr><td colspan="4">{{ __('reporting.empty') }}</td></tr>@endforelse</tbody></table></div>{{ $late->links('pagination::tailwind') }}</x-backend.card>
    <x-backend.card :title="__('reporting.delivery')"><div class="overflow-x-auto"><table class="qpos-table w-full text-sm"><thead><tr><th>{{ __('reporting.user_id') }}</th><th>{{ __('reporting.state') }}</th><th>{{ __('reporting.attempts') }}</th><th>{{ __('reporting.error') }}</th></tr></thead><tbody>@foreach($deliveries as $d)<tr><td class="p-2">{{ $d->user_id }}</td><td class="p-2">{{ __('reporting.delivery_'.$d->state) }}</td><td class="p-2">{{ $d->attempts }}</td><td class="p-2">{{ $d->last_error ? __('reporting.'.$d->last_error) : '—' }}</td></tr>@endforeach</tbody></table></div>{{ $deliveries->links('pagination::tailwind') }}</x-backend.card>
@endsection
