<!doctype html><html lang="{{ app()->getLocale() }}"><head><meta charset="utf-8"><title>{{ __('Invoice') }} #{{ $order->id }}</title>
<style>@page{size:{{ $ticket?'auto':'A4' }};margin:{{ $ticket?'3mm':'12mm' }}}*{box-sizing:border-box}body{font:{{ $ticket?'11':'12' }}px Arial,sans-serif;color:#111;margin:0 auto;width:{{ $ticket?'74mm':'100%' }}}h1{font-size:17px}table{width:100%;border-collapse:collapse;margin:12px 0}th,td{padding:5px 2px;text-align:left;border-bottom:1px solid #ddd}.amount{text-align:right}tr{break-inside:avoid}thead{display:table-header-group}.totals{margin-left:auto;width:{{ $ticket?'100%':'55%' }};break-inside:avoid}.note{font-size:10px}button,a.no-print{display:inline-flex;align-items:center;justify-content:center;min-width:44px;min-height:44px;padding:8px;margin:4px 4px 0 0}td{overflow-wrap:anywhere}@media print{button,a.no-print{display:none}}</style></head><body>
@php($snapshot=$order->checkout_snapshot ?? [])
<h1>{{ readConfig('site_name') ?: 'QPOS' }}</h1><p>{{ __('Invoice') }} #{{ $order->id }} · XAF</p>
<p>{{ ($snapshot['customer_label'] ?? $order->customer->name) === 'Walking Customer' ? __('Walking Customer') : ($snapshot['customer_label'] ?? $order->customer->name) }}<br>{{ Illuminate\Support\Carbon::parse($order->created_at,'UTC')->timezone('Africa/Douala')->format('d/m/Y H:i') }} · {{ __('Cash session') }} #{{ $order->cash_session_id }}</p>
<table><thead><tr><th>{{ __('Product') }}</th><th>{{ __('Quantity') }}</th><th class="amount">{{ __('Total') }}</th></tr></thead><tbody>
@foreach($order->products as $p)<tr><td>{{ $p->product_label_snapshot }}<br><small>{{ $p->packaging_label_snapshot }} · {{ App\Support\SaleFormat::quantityDisplay($p->base_quantity) }} {{ __('base units') }}</small><br><small>{{ App\Support\SaleFormat::moneyDisplay($p->price) }} XAF · {{ __('Discount') }} {{ App\Support\SaleFormat::moneyDisplay($p->discount) }}</small></td><td>{{ App\Support\SaleFormat::quantityDisplay($p->quantity) }}</td><td class="amount">{{ App\Support\SaleFormat::moneyDisplay($p->total) }}</td></tr>@endforeach
</tbody></table>
<table class="totals"><tr><td>{{ __('Subtotal') }}</td><td class="amount">{{ App\Support\SaleFormat::moneyDisplay($snapshot['sub_total'] ?? $order->sub_total) }}</td></tr><tr><td>{{ __('Discount') }}</td><td class="amount">{{ App\Support\SaleFormat::moneyDisplay($snapshot['discount'] ?? $order->discount) }}</td></tr><tr><td>{{ __('Rounding') }}</td><td class="amount">{{ App\Support\SaleFormat::moneyDisplay($order->rounding_adjustment) }}</td></tr><tr><th>{{ __('Total') }}</th><th class="amount">{{ App\Support\SaleFormat::moneyDisplay($order->total) }} XAF</th></tr><tr><td>{{ __('Paid') }}</td><td class="amount">{{ App\Support\SaleFormat::moneyDisplay($snapshot['paid'] ?? $order->paid) }}</td></tr><tr><td>{{ __('Store credit') }}</td><td class="amount">{{ App\Support\SaleFormat::moneyDisplay($snapshot['credit_used'] ?? $order->credit_used) }}</td></tr><tr><td>{{ __('Change') }}</td><td class="amount">{{ App\Support\SaleFormat::moneyDisplay($snapshot['change_amount'] ?? $order->change_amount) }}</td></tr><tr><td>{{ __('Due at sale') }}</td><td class="amount">{{ App\Support\SaleFormat::moneyDisplay($snapshot['due'] ?? $order->due) }}</td></tr></table>
@foreach($snapshot['payments'] ?? [] as $p)<p>{{ __($p['method']) }}: {{ App\Support\SaleFormat::moneyDisplay($p['amount']) }} XAF @if(!empty($p['external_reference'])) · {{ $p['external_reference'] }} @endif</p>@endforeach
@if(($snapshot['exchange_value'] ?? $order->exchange_value)>0)<p>{{ __('Exchange settlement') }}: {{ App\Support\SaleFormat::moneyDisplay($snapshot['exchange_value'] ?? $order->exchange_value) }} XAF</p>@endif<p class="note">{{ __('Thank you for your purchase.') }}</p><button onclick="window.print()">{{ __('Print') }}</button><a class="no-print" href="{{ route('backend.admin.cart.index') }}">{{ __('POS') }}</a>
</body></html>
